language: python
python:
  - 2.6
  - 2.7
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
install:
  - pip install nose
  - pip install -q Django==$DJANGO --use-mirrors
script:
  - python setup.py test
notifications:
  email:
    - henning.kage@gmail.com