language: python
python:
  - 2.7
env:
  - DJANGO=1.3.7
  - DJANGO=1.4.5
  - DJANGO=1.5.1
install:
  - pip install nose
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install coveralls --use-mirrors
script:
  - coverage run python setup.py test
after_success:
  - coveralls
notifications:
  email:
    - henning.kage@gmail.com